jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello world"
name: Publish release
on:
  release:
    types:
      - published
      - released
